name: 'Run and Capture Error'
description: 'Run a command and capture any errors with specified log file path'
inputs:
  command:
    description: 'The command to run'
    required: true
  step-name:
    description: 'Name of the step for logging purposes'
    required: true
  error-log-path:
    description: 'Absolute path to the error log file'
    required: true
    default: 'errors.txt'
runs:
  using: 'composite'
  steps:
    - run: |
        echo " ${{ inputs.command }} - ${{ inputs.error-log-path }} - ${{ inputs.step-name }} 
        dsadasdasd ?>> ${{ inputs.error-log-path }}
        # ${{ inputs.command }} 2>> ${{ inputs.error-log-path }} || echo "Step failed: [${{ inputs.step-name }}]" >> ${{ inputs.error-log-path }}
      shell: bash
